---
##
# Apache2 setup.
#

- name: Apache | Enable required Apache modules
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
  - proxy
  - proxy_http
  - rewrite
  - ssl

- name: Apache | Disable the default site
  action: command a2dissite 000-default
  ignore_errors: yes  
      
- name: Apache | Configure Apache
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
  with_items: "{{apache_ports_configuration_items}}"
  notify:
  - apache restart      
      
- name: Apache | Compile Apache Jenkins configuration
  template: src=apache.conf.j2 dest=/etc/apache2/sites-available/jenkins.conf

- name: Apache | Enable our Jenkins site
  action: command a2ensite jenkins
  notify:
  - apache restart
