---

- name: jenkins-auth | Encrypt http auth passwords
  htpasswd:
    name: "{{item.name}}"
    password: "{{item.password}}"
    path: "{{jenkins_home}}/.htpasswd"
  with_items: "{{jenkins_proxy_auth_users}}"
  when: jenkins_proxy_auth
