---

- name: jenkins-configure | Configure Jenkins
  template: src=jenkins.j2 dest={{jenkins_configuration}}
  register: jenkins_configure

- name: Create {{ jenkins_home }} folder
  file: path={{ jenkins_home }} state=directory mode=0755 owner={{ jenkins_user }}
  ignore_errors: True
  
- name: jenkins-configure | Ensure Jenkins restarted
  service: name=jenkins state=restarted
  when: jenkins_configure.changed

- name: Wait untils Jenkins web API is available
  shell: curl --head --silent http://localhost:{{ jenkins_http_port }}{{ jenkins_prefix }}/cli/
  retries: 12
  until: result.stdout.find("200 OK") != -1
  delay: 10
  register: result
  changed_when: False
  when: jenkins_configure.changed
  
- name: jenkins-configure | Copy jenkins-cli
  get_url: url=http://localhost:{{jenkins_http_port}}{{ jenkins_prefix }}/jnlpJars/jenkins-cli.jar dest={{jenkins_home}}/jenkins-cli.jar
  register: jenkins_cli
  until: "'OK' in jenkins_cli.msg or 'file already exists' in jenkins_cli.msg"
  retries: 10
  delay: 10
  when: jenkins_plugins or jenkins_jobs

- name: Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/jenkins.conf
  when: jenkins_logrotate
