---

- name: jenkins-configure | Ensure Jenkins is stopped
  service: name=jenkins state=stopped
  sudo: yes

- name: jenkins-configure | Create home folder
  file:
    mode: 0755
    owner: "{{ jenkins_user }}"
    path: "{{ jenkins_home }}"
    state: directory
  sudo: yes
  ignore_errors: True

- name: jenkins-configure | Create {{ jenkins_home }} with full rights for vagrant
  file: state=directory mode=0777 path={{ jenkins_home }} owner=vagrant group=vagrant
  sudo: yes
  when: jenkins_remote_enabled

- name: jenkins-configure | Change permission for vagrant
  file: path={{jenkins_home}} owner=vagrant group=vagrant recurse=yes
  sudo: yes
  when: jenkins_remote_enabled

- name: jenkins-configure | Configure Jenkins service
  template:
    dest: "{{jenkins_configuration}}"
    src: jenkins.j2
  sudo: yes
  register: jenkins_service_configure

#- name: jenkins-configure | Modify variables in init file
#  lineinfile:
#    dest: "{{ jenkins_configuration }}"
#    insertafter: '^{{ item.option }}='
#    regexp: '^{{ item.option}}=\"\${{ item.option }} '
#    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
#    state: present
#  sudo: yes
#  with_items:
#      "{{ jenkins_init_changes }}"
#  register: jenkins_init_prefix

- name: jenkins-configure | Add Jenkins key for remote access using vagrant
  authorized_key: user=vagrant key="{{ lookup('file', "{{ jenkins_remote_ssh_rsa }}") }}"
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  ignore_errors: True
#  become: yes

- name: jenkins-configure | Restore configuration from backup
  #synchronize: mode=pull src={{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_backup }} dest="{{ jenkins_home }}/" rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--compress
  command: rsync -lptgoD --rsh='ssh -i {{ jenkins_remote_rsa }}' {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_backup }}/* {{ jenkins_home }}/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
#TODO try become
#  become: true
#  become_method: sudo
#  become_user: jenkins
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Restore users from master
  #synchronize: mode=pull src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/users/" dest={{ jenkins_home }}/users/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  command: rsync -a --rsh='ssh -i {{ jenkins_remote_rsa }}' {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/users/ {{ jenkins_home }}/users/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Restore jobs from master
  command: rsync -a --exclude 'builds' --rsh='ssh -i {{ jenkins_remote_rsa }}' {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/jobs/ /jenkins/jobs/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Restore userContent from master
  command: rsync -a --rsh='ssh -i {{ jenkins_remote_rsa }}' {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:/jenkins/userContent/ /jenkins/userContent/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Enable groovy scripts
  shell: sed -i "s;<permission>hudson.model.Hudson.RunScripts:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Hudson.RunScripts:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Enable swarm connect for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Connect:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Connect:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled and jenkins_swarm_enabled

- name: jenkins-configure | Enable swarm create for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Create:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Create:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled and jenkins_swarm_enabled

- name: jenkins-configure | Set ownership on all jenkins files
  file: path={{ jenkins_home }} owner={{ jenkins_user }} group={{ jenkins_group }} state=directory recurse=true
  sudo: yes
  #when: jenkins_service_configure.changed

- name: jenkins-configure | Remove Jenkins security init scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent
  sudo: yes

- name: Restore configuration from backup
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_backup }}" dest=/jenkins/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Restore plugins from master
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/plugins/" dest=/jenkins/plugins/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Restore users from master
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/users/" dest=/jenkins/users/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Restore config from master
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/config.xml" dest=/jenkins/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Enable groovy scripts
  shell: sed -i "s;<permission>hudson.model.Hudson.RunScripts:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Hudson.RunScripts:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Enable swarm connect for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Connect:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Connect:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled && jenkins_swarm_enabled

- name: Enable swarm create for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Create:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Create:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled && jenkins_swarm_enabled

- name: Create {{ jenkins_home }} folder
  file: path={{ jenkins_home }} state=directory mode=0755 owner={{ jenkins_user }}
  sudo: yes
  ignore_errors: True

- name: Set ownership on all {{ jenkins_home }} files
  file: path={{ jenkins_home }} owner={{ jenkins_user }} group={{ jenkins_group }} state=directory recurse=true
  sudo: yes

- name: jenkins-configure | Ensure Jenkins restarted if needed
  service:
    name: jenkins
    state: restarted
  changed_when: False
  sudo: yes
  #when: jenkins_service_configure.changed and jenkins_restart_enabled
  when: jenkins_restart_enabled

- name: jenkins-configure | Ensure Jenkins running
  service:
    name: jenkins
    state: started
  changed_when: False
  sudo: yes
  when: not jenkins_service_configure.changed

- name: jenkins-configure | Wait untils Jenkins web API is available
  shell: curl --head --silent {{ jenkins_url }}/cli/
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  register: result
  changed_when: False
  #when: jenkins_service_configure.changed and jenkins_restart_enabled
  when: jenkins_restart_enabled

- name: jenkins-configure | Copy jenkins-cli
  get_url: url={{ jenkins_url }}/jnlpJars/jenkins-cli.jar dest={{ jenkins_home }}/jenkins-cli.jar
  register: jenkins_cli
  until: "'OK' in jenkins_cli.msg or 'file already exists' in jenkins_cli.msg"
  sudo: yes

  retries: 10
  delay: 10
  when: jenkins_restart_enabled

- name: jenkins-configure | Copy Groovy file to disable jobs
  copy: src=./files/DisableAllJobs.groovy dest={{ jenkins_home }}/DisableAllJobs.groovy owner=vagrant group=vagrant mode=0644
  sudo: yes

- name: jenkins-configure | Copy Groovy files to remove nodes
  copy: src=./files/RemoveAllNodes.groovy dest={{ jenkins_home }}/RemoveAllNodes.groovy owner=vagrant group=vagrant mode=0644
  sudo: yes

- name: jenkins-configure | Run groovy scripts
  shell: java -jar {{ jenkins_home }}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{ jenkins_http_port }}{{ jenkins_prefix }} -i {{ jenkins_remote_rsa }} groovy {{ item }}
  sudo: yes
  with_items:
    - ./files/DisableAllJobs.groovy
    - ./files/RemoveAllNodes.groovy
  when: jenkins_groovy_enabled and jenkins_restart_enabled

- name: jenkins-configure | Run groovy scripts
  shell: java -jar {{ jenkins_home }}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{ jenkins_http_port }}{{ jenkins_prefix }} -i {{ jenkins_remote_rsa }} groovy {{ item }}
  with_items:
    - ../Groovy/DisableAllJobs.groovy
    - ../Groovy/RemoveAllNodes.groovy
  when: jenkins_groovy_enabled
  when: jenkins_restart_enabled

- name: jenkins-configure | Configure Jenkins System
  template: src=jenkins_system_config.xml.j2 dest={{ jenkins_home }}/jenkins.model.JenkinsLocationConfiguration.xml owner={{ jenkins_user }} group={{ jenkins_group }} force=yes
  sudo: yes
  notify: jenkins reload configuration

- name: jenkins-configure | Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/jenkins.conf
  sudo: yes
  when: jenkins_logrotate
