---

- name: jenkins-configure | Configure Jenkins Service
  template: src=jenkins.j2 dest={{jenkins_configuration}}
  sudo: yes
  register: jenkins_service_configure

- name: Create home folder
  file: path={{ jenkins_home }} state=directory mode=0755 owner={{ jenkins_user }}
  sudo: yes
  ignore_errors: True

- name: Restore configuration from backup
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_backup }}" dest=/jenkins/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Restore plugins from master
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/plugins/" dest=/jenkins/plugins/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Restore users from master
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/users/" dest=/jenkins/users/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Restore config from master
  synchronize: src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/config.xml" dest=/jenkins/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--compress
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Enable groovy scripts
  shell: sed -i "s;<permission>hudson.model.Hudson.RunScripts:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Hudson.RunScripts:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: Enable swarm connect for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Connect:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Connect:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled && jenkins_swarm_enabled

- name: Enable swarm create for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Create:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Create:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  when: jenkins_service_configure.changed
  when: jenkins_remote_enabled && jenkins_swarm_enabled

- name: Create {{ jenkins_home }} folder
  file: path={{ jenkins_home }} state=directory mode=0755 owner={{ jenkins_user }}
  sudo: yes
  ignore_errors: True

- name: Set ownership on all {{ jenkins_home }} files
  file: path={{ jenkins_home }} owner={{ jenkins_user }} group={{ jenkins_group }} state=directory recurse=true
  sudo: yes

- name: jenkins-configure | Ensure Jenkins restarted
  service: name=jenkins state=restarted
  changed_when: False
  sudo: yes
  when: jenkins_service_configure.changed and jenkins_restart_enabled

- name: Wait untils Jenkins web API is available
  shell: curl --head --silent http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{ jenkins_prefix }}/cli/
  delay: 10
  retries: 12
  until: result.stdout.find("200 OK") != -1
  register: result
  changed_when: False
  when: jenkins_service_configure.changed and jenkins_restart_enabled

- name: jenkins-configure | Copy jenkins-cli
  get_url: url=http://{{ jenkins_http_host }}:{{ jenkins_http_port }}{{ jenkins_prefix }}/jnlpJars/jenkins-cli.jar dest={{ jenkins_home }}/jenkins-cli.jar
  register: jenkins_cli
  until: "'OK' in jenkins_cli.msg or 'file already exists' in jenkins_cli.msg"
  sudo: yes
  retries: 10
  delay: 10
  when: jenkins_restart_enabled

- name: jenkins-configure | Run groovy scripts
  shell: java -jar {{ jenkins_home }}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{ jenkins_http_port }}{{ jenkins_prefix }} -i {{ jenkins_remote_rsa }} groovy {{ item }}
  with_items:
    - ../Groovy/DisableAllJobs.groovy
    - ../Groovy/RemoveAllNodes.groovy
  when: jenkins_groovy_enabled
  when: jenkins_restart_enabled

- name: jenkins-configure | Configure Jenkins System
  template: src=jenkins_system_config.xml.j2 dest={{jenkins_home}}/jenkins.model.JenkinsLocationConfiguration.xml owner={{ jenkins_user }} group={{ jenkins_group }} force=yes
  sudo: yes
  notify: [jenkins reload configuration]

- name: Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/jenkins.conf
  sudo: yes
  when: jenkins_logrotate
