---

- name: jenkins-configure | Configure Jenkins Service
  template:
    dest: "{{ jenkins_configuration }}"
    src: jenkins.j2
  register: jenkins_service_configure

- name: jenkins-configure | Create home folder
  file:
    mode: 0755
    owner: "{{ jenkins_user }}"
    path: "{{ jenkins_home }}"
    state: directory

- name: jenkins-configure | Ensure Jenkins restarted if needed
  service:
    name: jenkins
    state: restarted
  changed_when: False
  when: jenkins_service_configure.changed and jenkins_restart_enabled

- name: jenkins-configure | Ensure Jenkins running
  service:
    name: jenkins
    state: started
  changed_when: False
  when: not jenkins_service_configure.changed

- name: Wait untils Jenkins web API is available
  shell: curl --head --silent {{ jenkins_url }}/cli/
  delay: 10
  retries: 12
  until: result.stdout.find("200 OK") != -1
  register: result
  changed_when: False
  when: jenkins_service_configure.changed and jenkins_restart_enabled

- name: jenkins-configure | Copy jenkins-cli
  get_url: url={{ jenkins_url }}/jnlpJars/jenkins-cli.jar dest={{ jenkins_home }}/jenkins-cli.jar
  register: jenkins_cli
  until: "'OK' in jenkins_cli.msg or 'file already exists' in jenkins_cli.msg"
  sudo: yes
  retries: 10
  delay: 10
  when: jenkins_restart_enabled

- name: jenkins-configure | Copy Groovy file to disable jobs
  copy: src=./files/DisableAllJobs.groovy dest={{ jenkins_home }}/DisableAllJobs.groovy owner=vagrant group=vagrant mode=0644
  sudo: yes

- name: jenkins-configure | Copy Groovy files to remove nodes
  copy: src=./files/RemoveAllNodes.groovy dest={{ jenkins_home }}/RemoveAllNodes.groovy owner=vagrant group=vagrant mode=0644
  sudo: yes

- name: jenkins-configure | Run groovy scripts
  shell: java -jar {{ jenkins_home }}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{ jenkins_http_port }}{{ jenkins_prefix }} -i {{ jenkins_remote_rsa }} groovy {{ item }}
  sudo: yes
  with_items:
    - ./files/DisableAllJobs.groovy
    - ./files/RemoveAllNodes.groovy
  when: jenkins_groovy_enabled and jenkins_restart_enabled

- name: jenkins-configure | Configure Jenkins System
  template: src=jenkins_system_config.xml.j2 dest={{ jenkins_home }}/jenkins.model.JenkinsLocationConfiguration.xml owner=jenkins group=jenkins force=yes
  notify: jenkins reload configuration

- name: jenkins-configure | Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/jenkins.conf
  when: jenkins_logrotate

