---

- name: jenkins-configure | Configure Jenkins service
  template:
    dest: "{{jenkins_configuration}}"
    src: jenkins.j2
  sudo: yes
  register: jenkins_service_configure

- name: jenkins-configure | Create home folder
  file:
    mode: 0755
    owner: "{{ jenkins_user }}"
    path: "{{ jenkins_home }}"
    state: directory
  become: yes
  ignore_errors: true

- name: jenkins-configure | Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
  become: yes

- name: jenkins-configure | Enable groovy scripts
  shell: sed -i "s;<permission>hudson.model.Hudson.RunScripts:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Hudson.RunScripts:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Enable swarm connect for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Connect:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Connect:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled and jenkins_swarm_enabled

- name: jenkins-configure | Enable swarm create for anonymous
  shell: sed -i "s;<permission>hudson.model.Computer.Create:{{ jenkins_swarm_user }}</permission>;<permission>hudson.model.Computer.Create:anonymous</permission>;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled and jenkins_swarm_enabled

#See https://wiki.jenkins-ci.org/display/JENKINS/Disable+security
- name: jenkins-configure | Disable security (In case Crowd is enabled) step 1
  shell: sed -i "s;<useSecurity>true</useSecurity>;<useSecurity>false</useSecurity>;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Disable security (In case Crowd is enabled) step 2
  shell: sed -i "s;<securityRealm class=\"de.theit.jenkins.crowd.CrowdSecurityRealm\";<\!--<securityRealm class=\"de.theit.jenkins.crowd.CrowdSecurityRealm\";g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Disable security (In case Crowd is enabled) step 3
  shell: sed -i "s;</securityRealm>;</securityRealm>-->;g" {{ jenkins_home }}/config.xml
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-configure | Set ownership on all jenkins files
  file: path={{ jenkins_home }} owner={{ jenkins_user }} group={{ jenkins_group }} state=directory recurse=true
  become: yes
  #when: jenkins_service_configure.changed

- name: jenkins-configure | Ensure Jenkins restarted if needed
  service:
    name: jenkins
    state: restarted
  changed_when: False
  become: yes
  #when: jenkins_service_configure.changed and jenkins_restart_enabled
  when: jenkins_restart_enabled

- name: jenkins-configure | Ensure Jenkins running
  service:
    name: jenkins
    state: started
  changed_when: False
  become: yes
  when: not jenkins_service_configure.changed

- name: jenkins-configure | Wait untils Jenkins web API is available
  shell: curl --head --silent {{ jenkins_url }}/cli/
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  register: result
  changed_when: False
  #when: jenkins_service_configure.changed and jenkins_restart_enabled
  when: jenkins_restart_enabled

- name: jenkins-configure | Remove Jenkins security init scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent
  become: yes

- name: jenkins-configure | Copy jenkins-cli
  get_url: url={{ jenkins_url }}/jnlpJars/jenkins-cli.jar dest={{ jenkins_home }}/jenkins-cli.jar
  register: jenkins_cli
  until: "'OK' in jenkins_cli.msg or 'file already exists' in jenkins_cli.msg"
  become: yes
  retries: 10
  delay: 10
  when: jenkins_restart_enabled

- name: jenkins-configure | Copy Groovy file to disable jobs
  copy: src=./files/DisableAllJobs.groovy dest={{ jenkins_home }}/init.groovy.d/DisableAllJobs.groovy owner={{ jenkins_user }} group={{ jenkins_group }} mode=0644
  become: yes

- name: jenkins-configure | Copy Groovy files to remove nodes
  copy: src=./files/RemoveAllNodes.groovy dest={{ jenkins_home }}/init.groovy.d/RemoveAllNodes.groovy owner={{ jenkins_user }} group={{ jenkins_group }} mode=0644
  become: yes

- name: jenkins-configure | Run groovy scripts
  # -i {{ jenkins_remote_rsa }}
  shell: java -jar {{ jenkins_home }}/jenkins-cli.jar -s {{ jenkins_url }} groovy {{ item }}
  become: yes
  with_items:
    - "{{ jenkins_home }}/init.groovy.d/DisableAllJobs.groovy"
    - "{{ jenkins_home }}/init.groovy.d/RemoveAllNodes.groovy"
  when: jenkins_groovy_enabled and jenkins_restart_enabled

- name: jenkins-configure | Configure Jenkins System
  template: src=jenkins_system_config.xml.j2 dest={{ jenkins_home }}/jenkins.model.JenkinsLocationConfiguration.xml owner={{ jenkins_user }} group={{ jenkins_group }} force=yes
  become: yes
  notify: jenkins reload configuration

- name: jenkins-configure | Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/jenkins.conf
  become: yes
  when: jenkins_logrotate
