---

- name: jenkins-install | Add apt key
  apt_key:
    id: "{{jenkins_apt_key_id}}"
    url: "{{ jenkins_apt_key }}"

- name: jenkins-install | Add apt repo
  apt_repository:
    repo: "{{ jenkins_apt_repository }}"
    update_cache: yes

- name: jenkins-install | Install jenkins
  apt:
    name: "{{item}}"
  with_items: "{{jenkins_apt_core_packages}}"

- name: jenkins-install | Install additional deb packages
  apt:
    name: "{{item}}"
  with_items: "{{jenkins_apt_packages}}"

- name: jenkins-install | Setup passlib
  apt:
    name: python-passlib
  when: jenkins_proxy_auth

# vim:sw=2
