---

- name: jenkins-install | Ensure Jenkins is stopped
  service: name=jenkins state=stopped
  ignore_errors: true
  become: yes

- name: jenkins-install | Kill connection used by user jenkins
  action: shell killall -u {{ jenkins_user }} || true
  changed_when: false
  become: yes
  ignore_errors: true
  when: jenkins_user != jenkins_target_user
  
- name: jenkins-install | Create a docker group
  group: 
      name=docker 
      state=present
  become: yes
  
- name: jenkins-install | Add user(s) to docker group
  user: 
      name={{ item }} 
      group=docker 
      state=present
  with_items: docker_users
  when: docker_users is defined
  become: yes

- name: jenkins-install | Create a jenkins group
  group: 
      name=jenkins 
      state=present
  become: yes
    
- name: jenkins-install | Create jenkins user
  user: name={{ jenkins_user }} password={{ jenkins_password }} update_password=always comment="Jenkins user" home={{ jenkins_home }} shell={{ jenkins_shell }} home={{ jenkins_home }} shell={{ jenkins_shell }} groups={{ jenkins_group }}
  become: yes
  ignore_errors: true

- name: jenkins-install | Create {{ jenkins_home }}
  file: state=directory mode=0755 path={{ jenkins_home }} owner={{ jenkins_user }} group={{ jenkins_group }}
  become: yes
  ignore_errors: true  
  when: jenkins_deb_enable

- name: jenkins-install | Test jenkins pkg package exists
  stat: path={{ jenkins_home }}/{{ jenkins_pkg_file }}
  become: yes
  register: jenkins_dir
  when: jenkins_deb_enable

- name: jenkins-install | Download jenkins pkg package
  get_url:
    url: "{{ jenkins_pkg_repository }}"
    dest: "{{ jenkins_home }}"
    mode: 0440
  become: yes
  when: jenkins_deb_enable and ( jenkins_dir.stat.exists == False )

- name: jenkins-install | Install jenkins
  action: command installer -pkg {{ jenkins_home }}/{{ jenkins_pkg_file }} -target /
  become: yes
  when: jenkins_deb_enable

# ls -lrta /Library/Application\ Support/Jenkins/

#TODO /usr/share/jenkins is protected on macosx
#    dest={{ jenkins_root }}
- name: jenkins-install | Link to Jenkins extracted Darwin package
  file:
    src=/Applications/Jenkins/
    dest=/usr/local/jenkins
    state=link
  become: yes
  when: ansible_distribution == 'MacOSX'  

#- name: jenkins-install | Link to Jenkins Home
#  file:
#    src=/Users/Shared/Jenkins/Home/
#    dest={{ jenkins_home }}
#    state=link
#  become: yes
#  when: ansible_distribution == 'MacOSX'

# vim:sw=2
