---

- name: jenkins-install | Add apt key
  apt_key:
    id: "{{ jenkins_apt_key_id }}"
    url: "{{ jenkins_apt_key }}"

- name: jenkins-install | Add apt repo
  apt_repository:
    repo: "{{ jenkins_apt_repository }}"
    update_cache: yes
  become: yes

- name: jenkins-install | Create {{ jenkins_home }}
  file: state=directory mode=0755 path={{ jenkins_home }} owner={{ jenkins_user }} group={{ jenkins_group }}
  become: yes
  ignore_errors: true  
  when: jenkins_deb_enable

- name: jenkins-install | Test jenkins deb package exists
  stat: path={{ jenkins_home }}/{{ jenkins_deb_file }}
  become: yes
  register: jenkins_dir
  when: jenkins_deb_enable

- name: jenkins-install | Download jenkins deb package
  get_url:
    url: "{{ jenkins_deb_repository }}"
    dest: "{{ jenkins_home }}"
    mode: 0440
  become: yes
  when: jenkins_deb_enable and ( jenkins_dir.stat.exists == False )

- name: jenkins-install | Install java
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items:
   - openjdk-7-jre-headless
  when: jenkins_deb_enable and ansible_distribution_version in ['12.04', '14.04']

- name: jenkins-install | Install java
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items:
   - openjdk-8-jre-headless
  when: jenkins_deb_enable and ansible_distribution_version not in ['12.04', '14.04']

- name: jenkins-install | Install daemon and net-tools
  apt: pkg={{ item }} state=present update_cache=yes
  become: yes
  with_items:
   - daemon
   - net-tools
  when: jenkins_deb_enable

- name: jenkins-install | Install jenkins
  action: command dpkg -i {{ jenkins_home }}/jenkins_{{ jenkins_version }}_all.deb
  become: yes
  when: jenkins_deb_enable

- name: jenkins-install | Install jenkins
  apt:
    name: "{{item}}"
  with_items: "{{jenkins_apt_core_packages}}"
  become: yes
  when: not jenkins_deb_enable

- name: jenkins-install | Install additional deb packages
  apt:
    name: "{{item}}"
  become: yes
  with_items: "{{jenkins_apt_packages}}"

- name: jenkins-install | Setup passlib
  apt:
    name: python-passlib
  become: yes
  when: jenkins_proxy_auth

# vim:sw=2
