---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [jenkins, jenkins-install]

- include: configure.yml
  tags: [jenkins, jenkins-configure]

- include: nginx.yml
  when: jenkins_nginx_proxy
  tags: [jenkins, jenkins-nginx]
