---

# - name: Include OS-specific variables.
  # include_vars: "{{ ansible_os_family }}.yml"
  # when: ansible_os_family == 'RedHat'

# - name: Include OS-specific variables.
  # include_vars: "{{item}}"
  # with_first_found:
  # - "{{ ansible_os_family }}-{{ ansible_lsb.codename }}.yml"
  # - "Debian-default.yml"
  # when: ansible_os_family == 'Debian'
  
- import_tasks: jenkins.yml
  when: jenkins_enabled
  tags: [jenkins]

# - import_tasks: checkjobs.yml
  # when: jenkins_check_jobs
  # tags: [jenkins]
  
