---

- file: path={{jenkins_home}}/updates owner={{jenkins_user}} group={{jenkins_group}} mode=0755 state=directory
  become: yes

- name: jenkins-plugins | Update Jenkins plugin data.
  shell: curl -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /{{jenkins_home}}/updates/default.json
    creates=/{{jenkins_home}}/updates/default.json
  become: yes

- name: jenkins-plugins | Change permission.
  file: path={{jenkins_home}}/updates/default.json owner={{jenkins_user}} group={{jenkins_group}} mode=0755
  become: yes

- name: jenkins-plugins | Install Jenkins plugins.
  command: java -jar {{jenkins_home}}/jenkins-cli.jar {{jenkins_cli_extra_opts}} -s {{jenkins_url}} install-plugin {{item}} creates={{jenkins_home}}/plugins/{{item}}.jpi
  become_user: "{{ jenkins_user }}"
  become: yes
  become_method: '{{ jenkins_become_method }}'
  with_items: "{{jenkins_plugins}}"
  ignore_errors: yes
  notify:
  - jenkins check web ready
  - jenkins check cli ready
  - jenkins restart

- name: jenkins-plugins | Activate plugins if disabled
  command: rm {{jenkins_home}}/plugins/{{item}}.jpi.disabled
  become: yes
  with_items: "{{jenkins_plugins}}"
  ignore_errors: yes
  notify:
  - jenkins check web ready
  - jenkins check cli ready
  - jenkins restart

- name: jenkins-plugins | Make sure plugins are disabled
  command: touch {{jenkins_home}}/plugins/{{item}}.jpi.disabled
  become: yes
  with_items: "{{jenkins_disabled_plugins}}"
  ignore_errors: yes
  notify:
  - jenkins check web ready
  - jenkins check cli ready
  - jenkins restart
