---

- name: jenkins-refresh | Ensure Jenkins is stopped
  service: name=jenkins state=stopped
  become: yes

- name: jenkins-refresh | Create home folder
  file:
    mode: 0755
    owner: "{{ jenkins_user }}"
    path: "{{ jenkins_home }}"
    state: directory
  become: yes
  ignore_errors: true

- name: jenkins-refresh | Create {{ jenkins_home }} with full rights for {{ jenkins_target_user }}
  file: state=directory mode=0755 path={{ jenkins_home }} owner={{ jenkins_target_user }} group={{ jenkins_target_group }}
  become: yes
  when: jenkins_remote_enabled

- name: jenkins-refresh | Change permission for {{ jenkins_target_user }}
  file: path={{jenkins_home}} owner={{ jenkins_target_user }} group={{ jenkins_target_group }} recurse=yes
  become: yes
  when: (jenkins_user != jenkins_target_user) and jenkins_remote_enabled


#BELOW is  done by hand for security reason
#TODO replace ssh-rsa hard code by jenkins_ssh_authorized_keys_fingerprints
#- name: jenkins-refresh | Add passwordless connection for remote user
#  authorized_key: user={{ jenkins_remote_user }} key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyTZc0ySGrGc2Fkl0ZrNc5iour4+CfQBUjgCR7Cy7eyG2vwIJb1lHrzIRxrEusz9fF4aUE7cMO6HTkUsAGg0g0B6A42/vhWVYanZAl26z9kNbT80UrKgvw6T4hJ602Q4bFQ4ODqM/UGJh18Xk4Wsj3mRRvmIyQ7TokWVevYKLmc96RdMtRlB8nFxcGfcVS0FQuADxVQF55wn7857C6VzbihOpAwndVZZTIGjXmsLNrthhYMwJcDzN8fSdhfyb7mbYDIxz931XAZqxv+fDagvfsurCcpL4X4fSXFhF2dZMN21Qng9VaHxQg2psr7/PgOSE5sY4hMhcbpRAr72E6yjnZ mgr.jenkins"
#  delegate_to: "{{ jenkins_remote_delegated_ip }}"
#  become: yes

- name: jenkins-refresh | jenkins-ssh from file| Copy private key
  copy: >
    src={{jenkins_ssh_key_file}}
    dest={{jenkins_target_home}}/.ssh/id_rsa
    owner={{jenkins_target_user}}
    group={{jenkins_target_group}}
    mode=0600
  when: jenkins_ssh_key_file != ""
  become: yes

- name: jenkins-refresh | Restore configuration from backup
  #synchronize: mode=pull src={{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_backup }} dest="{{ jenkins_home }}/" rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--compress
  #--rsh='ssh -i {{ jenkins_remote_rsa }}'
  command: rsync -lptgoD {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_backup }}/* {{ jenkins_home }}/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
#TODO try become
#  become: true
#  become_method: sudo
#  become_user: jenkins
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-refresh | Restore users from backup
  #synchronize: mode=pull src="{{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/users/" dest={{ jenkins_home }}/users/ rsync_opts=--rsh='ssh -i {{ jenkins_remote_rsa }}',--recursive,--compress
  #--rsh='ssh -i {{ jenkins_remote_rsa }}'
  command: rsync -a {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/users/ {{ jenkins_home }}/users/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-refresh | Restore jobs from backup
  #--rsh='ssh -i {{ jenkins_remote_rsa }}'
  command: rsync -a --exclude 'builds' {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/jobs/ {{ jenkins_home }}/jobs/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-refresh | Restore userContent from master
  #--rsh='ssh -i {{ jenkins_remote_rsa }}'
  command: rsync -a {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/userContent/ {{ jenkins_home }}/userContent/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-refresh | Restore plugin from master
  #--rsh='ssh -i {{ jenkins_remote_rsa }}'
  command: rsync -a {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/plugins/ {{ jenkins_home }}/plugins/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled and jenkins_remote_plugin_enabled

- name: jenkins-refresh | Restore email-templates from master
  #--rsh='ssh -i {{ jenkins_remote_rsa }}'
  command: rsync -a {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/email-templates/ {{ jenkins_home }}/email-templates/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled

- name: jenkins-refresh | Restore secrets from master
  #--rsh='ssh -i {{ jenkins_remote_rsa }}'
  command: rsync -a {{ jenkins_remote_user }}@{{ jenkins_remote_ip }}:{{ jenkins_remote_path }}/secrets/ {{ jenkins_home }}/secrets/
  delegate_to: "{{ jenkins_remote_delegated_ip }}"
  #when: jenkins_service_configure.changed
  when: jenkins_remote_enabled
