---

- name: jenkins restart
  docker_container:
    name: jenkins
    state: started
    restart: true

- name: nginx reload
  service: name=nginx state=reloaded
  become: yes
  
- name: apache restart
  service: name=apache2 state=restarted
  become: yes
