---

- name: jenkins restart
  service: name=jenkins state=restarted

- name: jenkins update jobs
  command: "{{jenkins_home}}/jobs/job.sh {{item.item.name}}"
  when: item.changed
  with_items: jenkins_jobs_changed.results

- name: jenkins reload configuration
  command: java -jar {{jenkins_home}}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{jenkins_http_port}}{{jenkins_prefix}} reload-configuration

- name: nginx reload
  service: name=nginx state=reloaded

- name: apache restart
  service: name=apache2 state=restarted
