---

- name: jenkins restart
  docker_container:
    name: jenkins
    state: started
    restart: true

- name: nginx reload
  service: name=nginx state=reloaded
  when: ansible_os_family != 'Darwin'  
  become: yes

- name: apache restart
  service: name=apache2 state=restarted
  when: ansible_os_family != 'Darwin'   
  become: yes
